[project]
name = "parameter-golf"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "datasets>=4.8.3",
    "huggingface-hub>=1.7.2",
    "mlx>=0.31.1",
    "numpy>=2.2.6",
    "sentencepiece>=0.2.1",
    "torch>=2.10.0",
    "tqdm>=4.67.3",
    "zstandard>=0.25.0",
]
